// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfdTUJErWv1kfyTiPkd1sD3hT0dyh2AAE',
    appId: '1:825988138895:web:81f7c1b556ad373168adfa',
    messagingSenderId: '825988138895',
    projectId: 'fir-mobile-7dc8a',
    authDomain: 'fir-mobile-7dc8a.firebaseapp.com',
    storageBucket: 'fir-mobile-7dc8a.appspot.com',
    measurementId: 'G-5180THYF8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLBsKebH-710GmRlL5vMG8-wUdY5x3f4',
    appId: '1:825988138895:android:d119b58fdf3164ce68adfa',
    messagingSenderId: '825988138895',
    projectId: 'fir-mobile-7dc8a',
    storageBucket: 'fir-mobile-7dc8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Z16JMn8fokk2Z8ixRGlmodcRwVRmJgc',
    appId: '1:825988138895:ios:41a99dfb3b20e2b568adfa',
    messagingSenderId: '825988138895',
    projectId: 'fir-mobile-7dc8a',
    storageBucket: 'fir-mobile-7dc8a.appspot.com',
    iosBundleId: 'com.example.flutterProyekUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Z16JMn8fokk2Z8ixRGlmodcRwVRmJgc',
    appId: '1:825988138895:ios:4174876be05cc5c668adfa',
    messagingSenderId: '825988138895',
    projectId: 'fir-mobile-7dc8a',
    storageBucket: 'fir-mobile-7dc8a.appspot.com',
    iosBundleId: 'com.example.flutterProyekUas.RunnerTests',
  );
}
